# Generated by Django 3.2.5 on 2021-08-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_see_all_borrower_books', 'View all borrower books'), ('can_bookinstance_accounting', 'Create, update and delete book instance'))},
        ),
    ]
